# Generated by Django 2.2.3 on 2019-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_talks', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='sort',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
