# Generated by Django 2.2.3 on 2019-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_talks', '0004_scientificcommittee_staticparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificcommittee',
            name='rule',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
