# Generated by Django 2.2.3 on 2019-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_talks', '0005_scientificcommittee_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificcommittee',
            name='image_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
